### ISSUE TITLE
Lab06_filename

### ISSUE THREAD

**Issue by june9666** [VIAUAC00/Android-labor#7]
Az adatbázis osztály létrehozása
A data package-ben hozzunk létre egy új Java osztályt, aminek a neve legyen **ShoppingItemDatabase**

....public abstract class **ShoppingListDatabase** extends RoomDatabase .....

_Should be declared in a file named **ShoppingListDatabase**._

**Comment by juhosistvan** [comment]
It really should be. This issue will be fixed in a few minutes.
